version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  users:
    build:
      context: ./service-users
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - gateway

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "85:85"
    depends_on:
      - users
      - gateway