version: '3.8'
services:
  users:
    build:
      context: ./service-users
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    network_mode: "host"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "85:85"
    depends_on:
      - users