version: '3.8'
services:
  gatekeeper:
    build:
      context: ./gatekeeper
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  users:
    build:
      context: ./service-users
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - gatekeeper

  loans:
    build:
      context: ./service-loans
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - gatekeeper